/*

Different Categories
monsters / creatures
background
scenary
scream
graphic
heads / faces
masks
gore
bw
dance
music
movement
weird / trippy

*/


const playlist = {
     
  bank: [
    {
      id: 0,
      trigger: "q",
      name: "Dance",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.11.53'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.14.21'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.14.48'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.17.00'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.18.02'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.18.42'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.20.26'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.21.38'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.22.21'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.23.09'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.24.52'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.26.40'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.27.42'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.28.49'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.30.48'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.34.30'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.36.04'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.38.01'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.38.36'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.40.37'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.43.33'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.46.02'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.48.02'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.50.03'},
        { 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-11201.32.47'},
      ],
    },
    {
      id: 1,
      trigger: "w",
      name: "Band",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_01'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_02'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_03'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_04'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_05'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_06'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_07'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_08'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_09'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_10'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_11'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_12'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_13'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_14'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_15'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_16'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_17'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_18'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_19'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_20'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_21'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_22'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_23'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_24'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_25'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_27'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_28'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_29'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_30'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_31'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_32'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_33'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_35'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_36'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_37'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_38'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_39'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_40'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_41'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_42'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_43'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_44'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_45'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_48'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_49'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_50'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_51'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_52'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_53'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_54'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_55'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_56'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_57'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_58'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_59'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_60'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_62'},
        { 'trigger' : 'q', 'location' : 'Animorphs/', 'name' : 'animorphs_63'},

      ]
    },
    {
      id: 2,
      trigger: "e",
      name: "Cartoons - Color",
      enabled: true,
      gifs: [        
        { 'trigger' : 'q', 'enabled' : false, 'location' : 'Halloween/ScoobyDoo/', 'name' : 'scooby-doo-bats-flying'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/ScoobyDoo/', 'name' : 'scooby-doo-ghost'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/ScoobyDoo/', 'name' : 'scooby-doo-seaman'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/ScoobyDoo/', 'name' : 'scooby-doo-secret-door-ghost'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/ScoobyDoo/', 'name' : 'scooby-doo-skulls'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Blackstar/', 'name' : 'blackstar_overlord'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Blackstar/', 'name' : 'blackstar_overlord_glowing_eyes'},

        { 'trigger' : 'q', 'enabled' : true, 'location' : 'SuperSeven/', 'name' : 'superSeven_sparkly_badGuy'},

        { 'trigger' : 'q', 'enabled' : true, 'location' : 'GalaxyRangers/', 'name' : 'galaxyRangers_bandBattle_75'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-10'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-11'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-12'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-14'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-15'},
        { 'trigger' : 'q', 'enabled' : false, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-3'},
        { 'trigger' : 'q', 'enabled' : false, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-4'},
        { 'trigger' : 'q', 'enabled' : false, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-5'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-6'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-7'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-9'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Skeletons/', 'name' : 'floating-skeleton-heads'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Misc/', 'name' : 'anime-split-fingers'},

        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_32'}, // color
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_38'},
      ]
    },
    {
      id: 3,
      trigger: "r",
      name: "",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_bed_grab_boy'},
        { 'trigger' : 'q', 'enabled' : false, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_hey_boy_grabbing'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_multi_clips'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_tall_man_chase_boy'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_tall_man_eye_multiplies'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_tall_man_multiplies'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_tall_man_portal'},
        { 'trigger' : 'q', 'enabled' : false, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_tall_man_stare'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_tall_man_walk'},

        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_49'}, 
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_50'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_51'},
        { 'trigger' : 'q', 'enabled' : false, 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_52'},

        { 'trigger' : 'q', 'enabled' : true, 'location' : 'Hercules/', 'name' : 'hercules_cave_eyes_flash_o'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'FantasticPlanet/', 'name' : 'fp_learning_head_2_REDO'},
        { 'trigger' : 'q', 'enabled' : true, 'location' : 'FantasticPlanet/', 'name' : 'fp_traag_hands_eyes_REDO'},
      ]
    },
    {
      id: 4,
      trigger: "t",
      name: "Monsters",
      enabled: true,
      gifs: [

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_15'}, // monster
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_16'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_17'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_18'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_19'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_20'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_21'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'blackula_01'}, // monster
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'blackula_02'}, 
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'bride-of-frankenstein'}, // monster
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_07'}, // monster / alien
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_32'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_35'}, // monster
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_36'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_37'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_62'}, // monster
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_63'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_65'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_60'},
        { 'trigger' : 'q', 'location' : 'Halloween/Dracula/', 'name' : 'dracula-blood-eyes'}, // monster
        { 'trigger' : 'q', 'location' : 'Halloween/Dracula/', 'name' : 'dracula-eyes'},
        { 'trigger' : 'q', 'location' : 'Halloween/Aliens/', 'name' : 'alien-creature-eyes'}, 
        { 'trigger' : 'q', 'location' : 'Halloween/Aliens/', 'name' : 'alien-monster-hands'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'upside-eye'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'wolf-man'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'woman-vampire'},

        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'skeleton-with-smoke'}, // skull
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_59'}, // skull 

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_01'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_02'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_03'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_04'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_05'}, 

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_75'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_76'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_77'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_78'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_79'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_80'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_81'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_82'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_83'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_84'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_85'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_42'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_43'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_45'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_46'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_47'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_53'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_55'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_56'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_58'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenMisc_22'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_02'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_03'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_04'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_05'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_06'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_07'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_09'},
      ]
    },
    {
      id: 5,
      trigger: "y",
      name: "Creepy",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'three-people-creepy-masks'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'ventriliquist-dummy'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'weird-old-man'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'scary-doll'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_09'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_10'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_13'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_25'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_26'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_27'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_14'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_28'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_29'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_30'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_66'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_67'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_68'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_69'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_70'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_71'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenMisc_23'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenMisc_24'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenMisc_25'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenMisc_26'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenMisc_27'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_18'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_25'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_22'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_20'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_24'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'ceiling-crawl'}, // creepy
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'creatures-from-ground'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'creepy-clown-hands'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'creepy-eyes'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'four-eyes-zoom-in'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'mutilated-monster-face'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'one-eyed-monster'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'red-eyes'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'scary-woman-blowing-out-candle'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'zoom-in-scary-woman'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'woman-arched-back'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_31'}, // creepy
        { 'trigger' : 'q', 'location' : 'Halloween/Masks/', 'name' : 'creepy-mask-kids'}, // creepy
        { 'trigger' : 'q', 'location' : 'Halloween/Masks/', 'name' : 'woman-mask-face'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_14'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_15'}, 
        { 'trigger' : 'q', 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_mustard_mouth'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'skeleton-in-rearview'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'skeleton-spinning-faces'},

        { 'trigger' : 'q', 'location' : 'Halloween/Zombies/', 'name' : 'thriller-zombie-heads'},
        { 'trigger' : 'q', 'location' : 'Halloween/Zombies/', 'name' : 'zombie-1'},
        { 'trigger' : 'q', 'location' : 'Halloween/Zombies/', 'name' : 'zombie-2'},
        { 'trigger' : 'q', 'location' : 'Halloween/Zombies/', 'name' : 'zombie-crowd'},
        { 'trigger' : 'q', 'location' : 'Halloween/Witches/', 'name' : 'witches-scaring-kids'},
      ]
    },
    {
      id: 6,
      trigger: "u",
      name: "Vintage Gifs",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : '3d-creeping-skeleton'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : '3d-friendly-ghost'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : '3d-walking-zombie'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'blood-dripping'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'bowl-of-fire'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'cauldron-with-fire'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'crow-and-skull'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'dripping-blood-line'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'flying-bat'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'green-ghost'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'lightning-2'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'line-of-flames'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'spectre-eyes-flashing'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'vampire-color-changing'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs//', 'name' : 'witch-crystal-ball'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs/Pumpkins/', 'name' : '8-bit-spinning-pumpkin'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs/Pumpkins/', 'name' : 'animated-pumpkin'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs/Pumpkins/', 'name' : 'flashing-pumpkin-face'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs/Pumpkins/', 'name' : 'flashing-pumpkin'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs/Pumpkins/', 'name' : 'pumpkin-face-2'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs/Pumpkins/', 'name' : 'scary-pumpkin'},
        { 'trigger' : 'q', 'location' : 'Halloween/VintageGifs/Pumpkins/', 'name' : 'spinning-pumpkins'},
      ]
    },    {
      id: 7,
      trigger: "i",
      name: "",
      enabled: false,
      gifs: [
      ]
    },
     
    {
      id: 8,
      trigger: "o",
      name: "",
      enabled: false,
      gifs: [
      ]
    },
    {
      id: 9,
      trigger: "p",
      name: "Scream & Kill",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_ball_drilling_head'},
        { 'trigger' : 'q', 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_ball_drilling_head2'},
        { 'trigger' : 'q', 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_cutting_fingers'},
        { 'trigger' : 'q', 'location' : 'FantasticPlanet/', 'name' : 'fp_deomizer-choking_REDO'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_22'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_23'},
        { 'trigger' : 'q', 'location' : 'Halloween/Blood/', 'name' : 'head-chop'},
        { 'trigger' : 'q', 'location' : 'Halloween/Blood/', 'name' : 'headless-squirting'},
        { 'trigger' : 'q', 'location' : 'Halloween/Blood/', 'name' : 'woman-sliced-throat'},
        { 'trigger' : 'q', 'location' : 'Halloween/Blood/', 'name' : 'bloody-body'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_18'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_06'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_08'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_11'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_12'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_10'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_11'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_12'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_13'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_14'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_15'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_16'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_17'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_21'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_23'},


        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_27'},

        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'the-fly-eyes'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'scared-woman'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_39'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_44'},
        { 'trigger' : 'q', 'location' : 'Halloween/Screaming/', 'name' : 'screaming-woman-2'},
        { 'trigger' : 'q', 'location' : 'Halloween/Screaming/', 'name' : 'woman-screaming'},
      ]
    },
     
    {
      id: 10,
      trigger: "a",
      name: "",
      enabled: false,
      gifs: [
      ]
    },
    {
      id: 11,
      trigger: "s",
      name: "",
      enabled: false,
      gifs: [ 
      ]
    },
    {
      id: 12,
      trigger: "d",
      name: "Halloween Cartoons - BW",
      enabled: true,
      colorPalette: ['#C01B05','#200706','#FC9016','#5C0405','#070602'],
      bankColorOpacity: .6,
      gradient: true,
      gifs: [

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_02'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_03'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_04'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_05'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_06'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_07'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_16'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_20'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_28'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_29'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_30'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_31'},

        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_39'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_40'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_41'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_42'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_43'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_44'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_45'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_46'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_47'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_48'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_49'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_50'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_51'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_52'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_53'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_54'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_55'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_66'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_67'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_70'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_71'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'animated-dancing-skeletons-4'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'cartoon-eyes'}, //eyes
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'animated-dancing-skeletons-18'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'cartoon-fighting-cats'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'cartoon-graveyard-scene'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'cartoon-jumping-skeleton'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'cartoon-owl'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'cartoon-throwing-head-skeleton'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'prancing-skeleton'},
        { 'trigger' : 'q', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.47.33'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'hauntedHouseCartoon_01'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'hauntedHouseCartoon_02'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'hauntedHouseCartoon_03'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'hauntedHouseCartoon_05'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'animated-dancing-skeletons-1'}, //movement
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'animated-dancing-skeletons-13'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'animated-dancing-skeletons-2'},
        { 'trigger' : 'q', 'location' : 'Halloween/Skeletons/', 'name' : 'animated-dancing-skeletons-3'},
      ]
    },
    {
      id: 13,
      trigger: "f",
      name: "",
      enabled: false,
      gifs: [
      ]
    },
    {
      id: 14,
      trigger: "g",
      name: "",
      enabled: false,
      gifs: [
      ]
    },
    {
      id: 15,
      trigger: "h",
      name: "Random",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'flies-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'maggot-cu-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'maggots-2-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'maggots-cu-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'maggots-cu2-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'maggots-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'roach-birth-1-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'roach-birth-2-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'roach-pan-1-fx_o'},
        { 'trigger' : 'q', 'location' : 'Insects/', 'name' : 'roach-pan-2-fx_o'},

        { 'trigger' : 'q', 'location' : 'Tekkonkinkreet/', 'name' : 'tekkon_eviltwin'},
        { 'trigger' : 'q', 'location' : 'Tekkonkinkreet/', 'name' : 'tekkon_minotaur1'},
        { 'trigger' : 'q', 'location' : 'Tekkonkinkreet/', 'name' : 'tekkon_minotaurdance'},
        { 'trigger' : 'q', 'location' : 'Tekkonkinkreet/', 'name' : 'tekkon_minotaurdistort'},
        { 'trigger' : 'q', 'location' : 'Tekkonkinkreet/', 'name' : 'tekkon_minotauropencape'},
        { 'trigger' : 'q', 'location' : 'Tekkonkinkreet/', 'name' : 'tekkon_minotaurshake'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : '2019-05-2921.15.41'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : '2019-05-2921.35.08'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : '2019-05-2922.07.44'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : '2019-05-2922.10.37'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : '2019-05-2922.29.06'},

        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'computerAnimation_face1'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'computerAnimation_face2'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'computerAnimation_face3'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'computerAnimation_face8'},
        
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'spinning_eggPeople1'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'spinning_eggPeople3'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'spinning_eggPeople4'},
        { 'trigger' : 'q', 'location' : 'NewGifs/', 'name' : 'spinning_eggPeople9'},
      ]
    },
    {
      id: 16,
      trigger: "j",
      name: "",
      enabled: false,
      gifs: [
      ]
    },
    {
      id: 17,
      trigger: "k",
      name: "March of the Dinosaurs",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.25.17'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.30.25'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.32.50'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.35.43'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.38.57'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.40.29'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.47.37'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.52.17'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.53.51'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.55.32'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.56.38'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2523.57.35'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.00.21'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.02.50'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.05.04'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.06.34'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.13.23'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.16.56'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.42.08'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.43.55'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.45.44'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.47.48'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.49.12'},

        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2601.03.30'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2601.12.01'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2601.14.37'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2601.15.54'},
      ]
    },
    {
      id: 18,
      trigger: "l",
      name: "",
      enabled: false,
      gifs: [
      ]
    },
     
    {
      id: 19,
      trigger: "z",
      name: "Halloween Background",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'Halloween/Phantasm/', 'name' : 'phantasm_house_vanishes'}, // bg
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'lightning-scary-house'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'speeding-scary-forest'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'candles-blown-out'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'bleeding-candle'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_48'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_61'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_64'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_57'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_54'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_38'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_34'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_33'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_72'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_73'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_74'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_26'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_28'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_08'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_01'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.56.16'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2601.01.14'},
        { 'trigger' : 'q', 'location' : 'MarchOfTheDinosaurs/', 'name' : 'MarchOfTheDinosaurs_2019-04-2600.09.11'},
        { 'trigger' : 'q', 'location' : 'Halloween/Lightning/', 'name' : 'lightning copy'}, // BG
        { 'trigger' : 'q', 'location' : 'Halloween/Lightning/', 'name' : 'lightning'},
        { 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_fire'}, // bg
        { 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_flythrough'},
        { 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-1_o'},
        { 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-2_o'},
        { 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-3_o'},
        { 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-4_o'},
        { 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-5_o'},
        { 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-house-explosion-1_o'},
        { 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.30.07'}, // BG
        { 'trigger' : 'q', 'location' : 'SuperSeven/', 'name' : 'superSeven_webWoman_transform'},
        { 'trigger' : 'q', 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-explosion-bolts'},
        { 'trigger' : 'q', 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-explosion'},
        { 'trigger' : 'q', 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-1'},
        { 'trigger' : 'q', 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-13'},
        { 'trigger' : 'q', 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-2'},
        { 'trigger' : 'q', 'location' : 'Halloween/Spiderman/', 'name' : 'spiderman-kotep-8'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenMisc_09'}, // bg
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_01'}, // bg
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_33'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_35'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_36'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenCartoons_37'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloweenBlackWhite_19'}, // bg
      ]
    },
    {
      id: 20,
      trigger: "x",
      name: "Spacey",
      enabled: true,
      gifs: [
        { trigger: "q", location: "WonderTwins/", name: "wondertwins_spiralSpin_o" },
        { trigger: "q", location: "BotP/", name: "botp_flashingLights_o" },
        { trigger: "q", location: "BotP/", name: "botp_lightBeams_o" },
        { trigger: "q", location: "BotP/", name: "botp_lightsFlashing_o" },
        { trigger: "q", location: "SpiralZone/", name: "spiralZone_2019-01-2603.18.48" },
        { 'trigger' : '', 'location' : 'VideoKids/', 'name' : 'videokids_18'},
        { 'trigger' : '', 'location' : 'SuperSeven/', 'name' : 'superSeven_explosion'},
        { 'trigger' : '', 'location' : 'SuperSeven/', 'name' : 'superSeven_explosion2'},
        { 'trigger' : '', 'location' : 'SuperSeven/', 'name' : 'superSeven_webWoman_transform'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_2'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_4'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_10'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_12'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_14'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_15'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_17'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_18'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_21'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_22'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_25'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2702.42.35'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2703.03.57'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2703.08.51'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2703.16.56'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2703.19.16'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2703.24.22'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2709.14.49'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2709.28.31'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2709.33.45'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2711.00.55'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2711.02.50'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2711.10.03'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2711.11.45'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2711.14.19'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2711.15.53'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2711.19.25'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2810.14.07'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2810.15.09'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_1'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_10'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_11'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_12'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_13'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_14'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_15'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_16'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_17'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_18'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_19'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_2'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_20'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_21'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_22'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_23'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_24'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_25'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_26'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_3'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_4'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_5'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_6'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_7'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_8'},
        // { 'trigger' : '', 'location' : 'ColoredGridShapes/', 'name' : 'coloredGridShapes_9'},
        { trigger: "q", location: "Misc/", name: "fantasticVoyage_spinningStripes_o" },
        { trigger: "q", location: "Hercules/", name: "hercules_explosion_stars" },
        { trigger: "q", location: "Hercules/", name: "hercules_green_beams" },
        { trigger: "q", location: "Hercules/", name: "hercules_movie_intro_1" },
        { trigger: "q", location: "Hercules/", name: "hercules_movie_intro_eye2_o" },
        { trigger: "q", location: "Hercules/", name: "hercules_movie_intro_eye3_o" },
        { trigger: "q", location: "Hercules/", name: "hercules_space_tunnel_explosion_o" },
        { trigger: "q", location: "Hercules/", name: "hercules_star_explosions" },
        { trigger: "q", location: "BotP/", name: "battleOfThePlanets_spaceStarLight_o" },
        { 'trigger' : '', 'location' : 'Blackstar/', 'name' : 'blackstar_space_explosion'},
        { trigger: "q", location: "Misc/", name: "kaleidoscope_pointed_muted" },
        { trigger: "q", location: "MissionSpatialeDelta2/", name: "msd_2018-03-0317.04.28" },
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2818.30.20'},
        { trigger: "q", location: "Misc/", name: "tvshow_man_floating_triangle_o" },
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_3'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_5'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_6'},
        { 'trigger' : '', 'location' : 'Unarius/', 'name' : 'unarious_16'},
      ]
    },
    {
      id: 21,
      trigger: "c",
      name: "ZOOM",
      enabled: true,
      gifs: [
        { trigger: "q", location: "Flythroughs/", name: "flythrough_a" },
        { trigger: "q", location: "Flythroughs/", name: "flythrough_g" },
        { trigger: "q", location: "Flythroughs/", name: "flythrough_n" },
        { trigger: "q", location: "Flythroughs/", name: "flythrough_o" },
        { trigger: "q", location: "Flythroughs/", name: "flythrough_q copy" },
        { trigger: "q", location: "Flythroughs/", name: "flythrough_q" },
        { trigger: "q", location: "Flythroughs/", name: "flythrough_s copy" },
        { trigger: "q", location: "Flythroughs/", name: "flythrough_s" },
        { trigger: "q", location: "CanyonFly/", name: "canyon_fly_1_o" },
        { trigger: "q", location: "CanyonFly/", name: "canyon_fly_2_o" },
        { trigger: "q", location: "CanyonFly/", name: "canyon_fly_2_o_t" },
        { trigger: "q", location: "CanyonFly/", name: "canyon_fly_3_o" },
        { trigger: "q", location: "CanyonFly/", name: "canyon_fly_3_o_t" },
        { trigger : 'q', location : 'Men/', name : 'Men_2019-04-0200.56.45'},
        { trigger : 'q', location : 'Men/', name : 'Men_2019-04-0200.57.42'},
        { trigger : 'q', location : 'Men/', name : 'Men_2019-04-0200.59.12'},
        { trigger: "q", location: "GridLines/", name: "h" },
        { trigger: "q", location: "GridLines/", name: "i" },
        { trigger: "q", location: "GridLines/", name: "m copy" },
        { trigger: "q", location: "GridLines/", name: "n copy" },
        { trigger: "q", location: "GridLines/", name: "r copy" },
        { trigger: "q", location: "GridLines/", name: "s" },
        { trigger: "q", location: "GridLines/", name: "t" },
        { trigger: "q", location: "GridLines/", name: "w copy" },
        { trigger: "q", location: "GridLines/", name: "w" },
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : 'castle_flythrough'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : 'castle_flythrough2'},
        { trigger: "q", location: "Misc/", name: "city-grid-2_o" },
        { trigger: "q", location: "Misc/", name: "city-grid_o" },
        { trigger: "q", location: "Misc/", name: "electro_pyramid_zoom" },
        { trigger: "q", location: "Misc/", name: "forbidden_world_hyperspace2" },
        { trigger: "q", location: "Misc/", name: "golden-flows_o" },
        { trigger: "q", location: "Misc/", name: "grid-open-doors_o" },
        { trigger: "q", location: "Misc/", name: "lit_wired_tunnel_o" },
        { trigger: "q", location: "Misc/", name: "rainbow_hypnotic_circles_o" },
        { trigger: "q", location: "Misc/", name: "rainbow_sparkler_zoom" },
        { trigger: "q", location: "Misc/", name: "spinning_space_planes" },
        { trigger: "q", location: "Misc/", name: "star_explosion_bubbles" },
        { trigger: "q", location: "Misc/", name: "ttriangular_infinity_morph_o" },
        { trigger: "q", location: "MissionSpatialeDelta/", name: "msd_flythrough_blocky_caverns_o" },
        { trigger: "q", location: "MissionSpatialeDelta/", name: "msd_geometric_cave_flythrough_o" },
        { trigger: "q", location: "MissionSpatialeDelta/", name: "msd_pink_space_clouds_o" },
        { trigger: "q", location: "MissionSpatialeDelta/", name: "msd_takeoff_tunnel_o" },
        { trigger: "q", location: "MissionSpatialeDelta/", name: "msd_tunnel_twist_o_t" },
        { trigger: "q", location: "MissionSpatialeDelta2/", name: "msd_2018-03-0322.21.01" },
        { trigger: "q", location: "MissionSpatialeDelta2/", name: "msd_2018-03-0322.43.52" },
        { trigger: "q", location: "MissionSpatialeDelta2/", name: "msd_2018-03-0319.17.18" },
        { trigger: "q", location: "AnimatedShorts/", name: "shattered_triangles_o" },
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : '2019-05-2918.46.05'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : 'fork_hallway1'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : 'fork_hallway2'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : 'fork_hallway3'},
        { 'trigger' : '', 'location' : 'NewGifs/', 'name' : 'fork_hallway4'},
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileAug08123439AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileAug08123703AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileJul1813902AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileJul1813914AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileJul1813937AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileJul1813947AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileJul1813957AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_FileJul184611AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_Jul1814018AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_Jul1814415AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_Jul1814457AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_Jul1814510AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_Jul1814521AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_Jul1814531AM" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_electrifying_organs" },
        { trigger: "q", location: "JapaneseAnims/", name: "japan_explosion_eray_tunnel_zoom_o" },
      ]
    },
    {
      id: 22,
      trigger: "v",
      name: "Bathbombs Matter",
      enabled: true,
      gifs: [
        { trigger: "q", location: "BathBombs/", name: "bathbomb-boomerang_o" },
        { trigger: "q", location: "BathBombs/", name: "bathbomb-galaxy-1_o" },
        { trigger: "q", location: "BathBombs/", name: "bathbomb-galaxy-2_o" },
        { trigger: "q", location: "BathBombs/", name: "bathbomb-slow-1_o" },
        { trigger: "q", location: "BathBombs/", name: "bathbomb-slow-2_o" },
        { trigger: "q", location: "BathBombs/", name: "bathbomb-spinner-1_o" },
        { trigger: "q", location: "BathBombs/", name: "bathbomb-spinner-2_o" },
        { trigger: "q", location: "BathBombs/", name: "bathbomb-spinner-blur_o" },
        { trigger: "q", location: "Ferrofluid/", name: "ferrofluid-burst_o" },
        { trigger: "q", location: "Ferrofluid/", name: "ferrofluid-pingpong-1_o" },
        { trigger: "q", location: "Ferrofluid/", name: "ferrofluid-pingpong-2_o" },
        { trigger: "q", location: "Ferrofluid/", name: "ferrofluid-pingpong-3_o" },
        { trigger: "q", location: "Ferrofluid/", name: "ferrofluid-symetrical-dance-2_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-1_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-1_transparent_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-2_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-2_transparent_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-3_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-3_transparent_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-4_o" },
        { trigger: "q", location: "FullTimeTrumpet/", name: "full-time-trumpet-FX-4_transparent_o" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.37.36_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.38.36_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.39.35_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.40.26_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.41.29_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.42.16_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.43.25_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.44.15_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.46.07_t" },
        { trigger: "q", location: "Matter/", name: "matterOne_2019-04-1300.46.55_t" },
        { trigger: "q", location: "Matter/", name: "matterTwo_2019-04-13-15.11.23_t" },
        { trigger: "q", location: "Matter/", name: "matterTwo_2019-04-13-15.12.09_t" },
        { trigger: "q", location: "Matter/", name: "matterTwo_2019-04-13-15.17.55_2t" },
        { trigger: "q", location: "Matter/", name: "matterTwo_2019-04-13-15.17.55_t" },
        { trigger: "q", location: "Matter/", name: "matterTwo_2019-04-14-16.35.15" },
        { trigger: "q", location: "Matter/", name: "matterTwo_2019-04-14-16.35.15_t" },
        { trigger: "q", location: "Misc/", name: "forest-forgery-1-B-FX1_o" },
        { trigger: "q", location: "Misc/", name: "forest-forgery-2-F2-FX_o" },
        { trigger: "q", location: "Rainbow/", name: "a" },
        { trigger: "q", location: "Rainbow/", name: "b" },
        { trigger: "q", location: "Rainbow/", name: "cruz-lights-1" },
        { trigger: "q", location: "Rainbow/", name: "cruz-lights-2" },
        { trigger: "q", location: "Rainbow/", name: "cruz-lights-3" },
        { trigger: "q", location: "Rainbow/", name: "cruz-lights-4" },
        { trigger: "q", location: "Rainbow/", name: "cruz-lights-5" },
        { trigger: "q", location: "Rainbow/", name: "d" },
        { trigger: "q", location: "Rainbow/", name: "e" },
        { trigger: "q", location: "Rainbow/", name: "f" },
        { trigger: "q", location: "Rainbow/", name: "g" },
        { trigger: "q", location: "Rainbow/", name: "h" },
        { trigger: "q", location: "Rainbow/", name: "i" },
        { trigger: "q", location: "Rainbow/", name: "j" },
        { trigger: "q", location: "Rainbow/", name: "o" },
        { trigger: "q", location: "Rainbow/", name: "p" },
        { trigger: "q", location: "Rainbow/", name: "patriotic-orb" },
        { trigger: "q", location: "Rainbow/", name: "rainbow-checker-tunnel" },
        { trigger: "q", location: "Rainbow/", name: "rainbow-gradients" },
        { trigger: "q", location: "Rainbow/", name: "spinning-checkered-pyramid" },
      ]
    },
    {
      id: 23,
      trigger: "b",
      name: "Circles",
      enabled: true,
      gifs: [
        { trigger: "q", location: "SpinningCircles/", name: "d" },
        { trigger: "q", location: "SpinningCircles/", name: "e" },
        { trigger: "q", location: "SpinningCircles/", name: "f" },
        { trigger: "q", location: "SpinningCircles/", name: "i copy" },
        { trigger: "q", location: "SpinningCircles/", name: "i" },
        { trigger: "q", location: "SpinningCircles/", name: "j copy" },
        { trigger: "q", location: "SpinningCircles/", name: "j" },
        { trigger: "q", location: "SpinningCircles/", name: "l" },
        { trigger: "q", location: "SpinningCircles/", name: "n" },
        { trigger: "q", location: "SpinningCircles/", name: "p" },
        { trigger: "q", location: "SpinningCircles/", name: "q" },
        { trigger: "q", location: "SpinningCircles/", name: "rainbow_hypnotic_circles_o" },
        { trigger: "q", location: "SpinningCircles/", name: "rainbow_sparkler_zoom" },
        { trigger: "q", location: "SpinningCircles/", name: "rainbow_spinning_circles" },
        { trigger: "q", location: "SpinningCircles/", name: "z" },
        { trigger: "q", location: "Eyes/", name: "eye_laser_sparkles_o" },
        { trigger: "q", location: "Eyes/", name: "eye_lasers_1_o" },
        { trigger: "q", location: "Eyes/", name: "eyes_r_o" },
        { trigger: "q", location: "Eyes/", name: "eyes_s_o" },
      ]
    },
    {
      id: 24,
      trigger: "n",
      name: "Graphic",
      enabled: true,
      gifs: [
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_01'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_02'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_03'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_04'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_05'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_06'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_07'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_08'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_09'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_10'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_12'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_13'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_16'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_17'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_19'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'outOfTheUnknown_20'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'someBody_2019-04-3009.31.31'},
        { 'trigger' : 'q', 'location' : 'Halloween/Misc/', 'name' : 'someBody_2019-04-3009.25.34'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'blackula_03'}, // graphic
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'blackula_05'},
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_40'}, // graphic
        { 'trigger' : 'q', 'location' : 'Halloween/NewTemp/', 'name' : 'halloween1970s_41'},
      ]
    },
    {
      id: 25,
      trigger: "m",
      name: "",
      enabled: false,
      gifs: [
      ]
    }
  ]
};