const appz = {
	"midiOn" : true,
	"defaultBeatTime" : 2000,
	"beatSpeed": 1000,
	"sameSameConstant" : 2,
	"overlaysEnabled" : true,
	"startupBankNumber" : 0,
	"startupBankTrigger" : "a",

	// "stageArray" : ['sf', 'st'],
	"blendModeArray" : ['screen','overlay'],

	"fontStyles" : ["Baloo Chettan", "Germania One", "Fascinate Inline", "Monoton", "Press Start 2P", "Spicy Rice"],

	"blendModes" : {
		"mix" : [
			{ "name": "multiply", "trigger": "1", "enabled": true },
			{ "name": "darken", "trigger": "1", "enabled": true },
			{ "name": "lighten", "trigger": "1", "enabled": true },
			{ "name": "color-dodge", "trigger": "1", "enabled": true },
			{ "name": "color-burn", "trigger": "1", "enabled": true },
			{ "name": "hard-light", "trigger": "1", "enabled": true },
			{ "name": "soft-light", "trigger": "1", "enabled": true },
			{ "name": "difference", "trigger": "1", "enabled": true },
			{ "name": "exclusion", "trigger": "1", "enabled": true },
			{ "name": "hue", "trigger": "1", "enabled": true },
			{ "name": "saturation", "trigger": "1", "enabled": true },
			{ "name": "color", "trigger": "1", "enabled": true },
			{ "name": "luminosity", "trigger": "1", "enabled": true }
		]
	},

	"filters" : {
		"strings": [
			{"value": ""},
			{"value": ""}
		],
	  "filter" : [
	    {
	      "name": "Invert",
	      "slugName": "invert",
	      "trigger": "7",
	      "min": 0,
	      "max": 1,
	      "unit": "",
	      "enabled": true,
	      "on": 0,
	      "stage": [
	        { "value": "" },
	        { "value": "" }
	      ]
	    },
	    {
	      "name": "Saturate",
	      "slugName": "saturate",
	      "trigger": "8",
	      "min": 1,
	      "max": 100,
	      "unit": "",
	      "enabled": true,
	      "on": 0,
	      "stage": [
	        { "value": "" },
	        { "value": "" }
	      ]
	    },
	    {
	      "name": "Hue Rotate",
	      "slugName": "hue-rotate",
	      "trigger": "9",
	      "min": 0,
	      "max": 360,
	      "unit": "deg",
	      "enabled": true,
	      "on": 0,
	      "stage": [
	        { "value": "" },
	        { "value": "" }
	      ]
	    },
	    {
	      "name": "Blur",
	      "slugName": "blur",
	      "trigger": "0",
	      "min": 0,
	      "max": 5,
	      "unit": "px",
	      "enabled": true,
	      "on": 0,
	      "stage": [
	        { "value": "" },
	        { "value": "" }
	      ]
	    }
	  ]
	},

	"effects": {
		"kaleidoscope": { "name": 'kaleidoscope', "enabled": true, "trigger": "1" },
		"mutator": { "name": 'mutator', "enabled": true, "trigger": "2" },
		"sameSame": { "name": 'sameSame', "enabled": true, "trigger": "3" },
		"stgFade": { "name": 'stgFade', "enabled": true, "trigger": "4" },
	},

	"overlays" : [
		{ 'trigger' : '1', 'location' : 'overlays', 'name' : 'clubMutoid_logo_ani.gif'},
	],


	"sequence" : [
		{
			"trigger": "a",
			"name" : "Some sequence",
			"enabled" : true,
			"scene" : [
				{
					"gifs" : [
						{ 'location' : 'BotP/', 'name' : 'battleOfThePlanets_keyopDiscoDance2_o' },
						{ 'location' : 'BotP/', 'name' : 'battleOfThePlanets_markFlipping_o' },
					]
				},
				{
					"gifs" : [
						{ 'location' : '4thStreetVine/', 'name' : 'forest-forgery-2-F2-FX_o' },
						{ 'location' : '4thStreetVine/', 'name' : 'golden-flows_o' },
					]
				},
				{
					"gifs" : [
						{ 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_kid_zap_robot_o' },
						{ 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_robot_dance_o' },
					]
				},
				{
					"gifs" : [
						{ 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.29.26' },
						{ 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.38.00' },
					]
				}
			]
		},
		{
			"trigger": "b",
			"name" : "Another sequence",
			"enabled" : false,
			"scene" : [
				{
					"gifs" : [
						{ 'location' : '4thStreetVine/', 'name' : 'robot_woman_head_back_o' },
						{ 'location' : '4thStreetVine/', 'name' : 'tvshow_man_floating_triangle_o' },
					]
				},
				{
					"gifs" : [
						{ 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_o' },
						{ 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_transparent_o' }
					]
				}
			]
		},
		{
			"trigger": "c",
			"name" : "Last sequence",
			"enabled" : true,
			"scene" : [
				{
					"gifs" : [
						{ 'location' : '4thStreetVine/', 'name' : 'robot_woman_head_back_o' },
						{ 'location' : '4thStreetVine/', 'name' : 'tvshow_man_floating_triangle_o' },
					]
				},
				{
					"gifs" : [
						{ 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_o' },
						{ 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_transparent_o' }
					]
				}
			]
		}
	],

	"bank" : [
		{
			"id" : 0,
			"trigger": "a",
			"name" : "Mission Spatiale Delta",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.26.06', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.40.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.43.01', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.48.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.55.43', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.57.50', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.04.28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.05.28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.07.47', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.15.09', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.17.29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.19.25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.23.44', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.25.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.37.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.52.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.53.28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.57.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.59.10', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.01.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.07.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.10.38', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.16.34', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.17.18', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.18.23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.20.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.48.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.52.32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.54.57', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.58.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.00.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.02.58', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.04.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.06.09', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.07.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.08.23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.10.42', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.15.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.20.16', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.21.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.23.54', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.29.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.38.00', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0321.28.04', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0321.47.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.03.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.05.05', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.09.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.13.57', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.15.27', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.16.05', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.21.01', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.29.06', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.30.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.35.13', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.37.31', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.43.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.48.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.50.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.03.14', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.27.03', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.30.23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.36.04', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.39.32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.41.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.43.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.46.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.48.41', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.51.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.04.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.06.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.18.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.26.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.27.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.30.38', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.32.57', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.36.40', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.39.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.43.17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.51.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.15.03', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.17.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.24.07', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.26.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_22018-03-0318.08.55', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_alienWoman_flyAround_orb2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_alienWoman_flyAround_orb_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_bat_punch_chop_robots_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_chased_by_wave', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_chased_by_wave2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_city_flythrough_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_explosing_balls', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_flashing_control_room', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_floating_hallway', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_flythrough_blocky_caverns', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_geometric_cave_flythrough_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_kicking_robots_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_lighted_tunnel_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_man_fighting_robots', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_orb_drags_rainbowRings_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_orb_glowing_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_pink_space_clouds', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_running_space_forest_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_ship_flying_into_spaceClouds_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_space_forest_log_jumping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_takeoff_tunnel', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_takeoff_tunnel_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_takeoff_tunnel_withOrb_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_tunnel_twist_o_t', 'set': 'm'}
			]
		},
		{
			"id" : 1,
			"trigger": "b",
			"name" : "Battle Of The Planets",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_discoBallLight_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_discoDancers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_jasonBumpingGlass_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_keyopDiscoDance2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_keyopDiscoDance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_markFlipping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_markOnGlass_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessFlipping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_spaceStarLight_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_banginSpoonsInCell2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_bangingSpoonInCell_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_computerScreens_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_flashingLights_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_lightBeams_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_lightsFlashing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_bass2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_bass3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_bass_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_cuGuitarHand_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_dancerCrowd_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_drummer2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_drummer_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_guitar2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_guitar3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_keyboards2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_keyboards_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studioCUDrummer_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_bass2_O', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_bass_O', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_drummer2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_drummerSlowZoom_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_drummer_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_guitar2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_keyboards_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceBand_studio_singer_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spaceband_singer_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spectograph2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spectograph_matchingWaves_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_spectrograph_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_trippyGalaxy_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_trippyRainbowTunnel_o', 'set': 'm'},
			]
		},
		{
			"id" : 2,
			"trigger": "c",
			"name" : "Aerobics",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_10', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_11', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_13', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_14', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_15', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_16', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_18', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_19', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_24', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_27', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_3', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_30', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_31', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_4', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_5', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_6', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_7', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_8', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_9', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_group1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_group1_o', 'set': 'm'},
			]
		},
		{
			"id" : 3,
			"trigger": "d",
			"name" : "Robots",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'egyptianLover_robotDance', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'egyptianLover_robotDance2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'fantastic-voyage-2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'fantastic-voyage-5', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'fantastic-voyage-8', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'gameboy_robotDance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'gameboy_robotShoot_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'mannMachine_robotHead_laserEyes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'mannMachine_robotHead_spin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'mannMachine_robotSpin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobot_flashingRobot_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobots _robot_boomerang_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobots_transformMan_explosion_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobots_transformMan_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'star-rider-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138-code_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138-screen-graphics-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138-screen-graphics-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138-screen-head_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138_screen-graphics-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138_screen-graphics_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138_screen-grid_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'tvbreak_robot_corridor', 'set': 'm'},
			]
		},
		{
			"id" : 4,
			"trigger": "e",
			"name" : "Rainbow",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'a', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'b', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'cruz-lights-1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'cruz-lights-2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'cruz-lights-3', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'cruz-lights-4', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'cruz-lights-5', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'd', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'e', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'f', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'g copy', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'g', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'h', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'i', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'j', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'l', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'p', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'patriotic-orb', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'rainbow-checker-tunnel', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'rainbow-gradients', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'spinning-checkered-pyramid', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'wind-up-robot', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Rainbow/', 'name' : 'wind-up-robot_o', 'set': 'm'},
			]
		},
		{
			"id" : 5,
			"trigger": "f",
			"name" : "Partridge Family Space",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_chris_drums2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_chris_drums_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_crowd_cheer_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_drumsticksPlaying_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_drumsticksPlaying_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_fingersOnGuitarStrings2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_fingersOnGuitarStrings_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_fingersOnGuitarStrings_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_keithAndKidsOutlines2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_keithAndKidsOutlines3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_keithAndKidsOutlines_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_keithGuitarOutlines2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_keithGuitarOutlines_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurieDancingTransformation_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingFire_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingFire_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines2_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines_keithGuitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingWavyLines_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingWavyLines_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_keyboards2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_keyboards_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_shirley_fingers_keyboard_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_shirley_keyboards_cu_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_shirley_keyboards_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_tracy_tambourines_o', 'set': 'm'},
			]
		},
		{
			"id" : 6,
			"trigger": "g",
			"name" : "Monkey Magic",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2721.23.59', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2721.26.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2721.29.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.47.34', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.51.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.53.34', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.56.17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2819.00.02', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2819.02.47', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2819.03.42', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2821.39.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2821.41.10', 'set': 'm'},
			]
		},
		{
			"id" : 7,
			"trigger": "h",
			"name" : "Kid Videos",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'bus-jump-ramp_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'cat-pooping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'dancing-hulk_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'dinosaur-spinning-heads_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'flying-trucks2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'garage-gorilla_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'garage-tiger-running_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'gorilla-punching-egg_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'hulk-step-walk_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'multiple-buses-jumping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'ramp-jumping-trucks_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'spinning-trucks_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'superhero-banana-car-fx_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'superhero-toilet-dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'swimming-hulk-fruit-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'swimming-hulk-fruit_o', 'set': 'm'},
			]
		},
		{
			"id" : 8,
			"trigger": "i",
			"name" : "Jungle",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'dancing_shield_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'dancing_shield_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_drone_bolivia_3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_drone_bolivia_3_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_game_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_game_1_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_game_2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_game_2_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_1_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_2_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_3_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'jungle_minecraft_4_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'man_walking_mushroom_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'man_walking_mushroom_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'men_fighting_snake_around_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jungle/', 'name' : 'spinning_around_moon_o', 'set': 'm'},
			]
		},
		{
			"id" : 9,
			"trigger": "j",
			"name" : "Josie Pussycats Space",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_alienCityScene_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_blonde_drumming_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_catAlien_pullHandle_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_intro_alien_hop_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_intro_cat_scratch_alien_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_intro_rocketFlying2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_intro_rocketFlying_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_redhead_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotDancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotHandOnHead_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotsRunningSmashed_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotsRunning_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_space_comets_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_tambourine_o', 'set': 'm'},
			]
		},
		{
			"id" : 10,
			"trigger": "k",
			"name" : "Jem",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_bandRockout_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_drumming_fire_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_drumming_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_drums2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_drums_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_flashing_stage_lights_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_guitar_and_keyboard_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_guitar_cu_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_hittingDrumPads_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_keyboardAndGuitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_keyboard_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_keyboards_and_drums_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_lips_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfit_fire_dance2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfit_fire_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfit_singer_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfits_on_stage_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfits_play2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfits_play_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_snake_takes_misfitGuitar_o', 'set': 'm'},
			]
		},
		{
			"id" : 11,
			"trigger": "l",
			"name" : "Japanese Anims",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileAug08123439AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileAug08123703AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813455AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813902AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813914AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813937AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813947AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813957AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1814555AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul184611AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814018AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814034AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814415AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814448AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814457AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814510AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814521AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814531AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814544AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_electrifying_organs', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_explosion_eray_tunnel_zoom_o', 'set': 'm'},
			]
		},
		{
			"id" : 12,
			"trigger": "m",
			"name" : "Bravestarr",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_band_hoedown_singer', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_bass_strum', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_golden_star_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_golden_star_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_guitar_strum_electricity', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_jumping_off_cliff_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_man_drumming_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_mind_control_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_oldMan_guitarElectricty', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_robot_band_playing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_running_animals_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_synth_band_playing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_woman_keytar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_woman_playing_keytar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_zoom_star_o', 'set': 'm'},
			]
		},
		{
			"id" : 13,
			"trigger": "n",
			"name" : "Dancing Trails - Canyon Fly",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_a', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_b', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_c', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_d', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_e', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_f', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_g', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_h', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_i', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'dancingtrails/', 'name' : 'dancingTrails_j', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_1_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_2_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_3_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_3_t', 'set': 'm'},
			]
		},
		{
			"id" : 14,
			"trigger": "o",
			"name" : "Animated Bands",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'billAndTed_guitar1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'billAndTed_guitar2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_bobby_drums_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_cindy_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_dancing_pandas2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_dancing_pandas_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_greg_guitar_bobby_drums_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_greg_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_jan_keyboards2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_jan_keyboards_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_marsha_tambourine2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_marsha_tambourine_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_peter_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'groovieGhoulies_countOnKeyboard_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'groovieGhoulies_floorKeyboard_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'groovieGhoulies_frankenstein_xylophone_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'groovieGhoulies_wolfman_strums_cu_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'groovieGhoulies_wolfman_strums_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'heroHigh_punker_play_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'jerryLewis_flamenco_dance1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'jerryLewis_flamenco_dance2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'jerryLewis_runningAroungScreen_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'missionMagic_rickGuitar_colorChange2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'missionMagic_rickGuitar_colorChange_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'myFavoriteMartian_two_guitars_playingThemselves_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'myFavoriteMartian_two_playing_guitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'myFavoriteMartian_two_playing_guitar_withDancers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_caveman_beats_drum_fast_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_caveman_beats_drum_slow_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_cu_legs_dancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_floating_record_turntable_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_friends_dancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_sabrina_dances_withClone_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_sabrina_friend_dances_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'silverhawks_strumming_guitar_cu_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'silverhawks_strumming_guitar_o', 'set': 'm'},
			]
		},
		{
			"id" : 15,
			"trigger": "p",
			"name" : "Spinning Circles",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'd', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'e', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'f', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'i copy', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'i', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'j copy', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'j', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'l', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'n', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'p', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'q', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'rainbow_hypnotic_circles', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'rainbow_hypnotic_circles_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'rainbow_sparkler_zoom', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'rainbow_spinning_circles', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpinningCircles/', 'name' : 'z', 'set': 'm'},
			]
		},
		{
			"id" : 16,
			"trigger": "q",
			"name" : "Action USA",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.11.53', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.14.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.14.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.17.00', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.18.02', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.18.42', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.20.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.21.38', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.22.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.23.09', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.24.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.26.40', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.27.42', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.28.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.30.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.34.30', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.36.04', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.38.01', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.38.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.40.37', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.43.33', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.46.02', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.48.02', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-1101.50.03', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'ActionUSA/', 'name' : 'actionUSA_2019-04-11201.32.47', 'set': 'm'}
			]
		},
		{
			"id" : 17,
			"trigger": "r",
			"name" : "Matter",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.37.36_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.38.36_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.39.35_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.40.26_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.41.29_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.42.16_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.43.25_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.44.15_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.46.07_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterOne_2019-04-1300.46.55_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-13-15.11.23_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-13-15.12.09_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-13-15.17.55_2t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-13-15.17.55_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-14-01.27.54', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-14-01.27.54_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-14-16.35.15', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Matter/', 'name' : 'matterTwo_2019-04-14-16.35.15_t', 'set': 'm'},
			]
		},
		{
			"id" : 18,
			"trigger": "s",
			"name" : "Bumble Boogie",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.28.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.32.11', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.33.32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.35.29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.39.57', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.42.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.46.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.49.54', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.51.19', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.52.17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.53.07', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.54.32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.55.43', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.57.16', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1922.58.25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.01.27', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.02.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.03.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.04.42', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.05.33', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.06.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.08.58', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.12.25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.13.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.14.15', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BumbleBoogie/', 'name' : 'bumbleBoogie_2019-04-1923.15.11', 'set': 'm'},
			]
		},
		{
			"id" : 19,
			"trigger": "t",
			"name" : "New Cartoons",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'WoodyWoodpecker/', 'name' : 'WoodyWoodpecker_2019-04-2400.54.24', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WoodyWoodpecker/', 'name' : 'WoodyWoodpecker_2019-04-2400.56.07', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WoodyWoodpecker/', 'name' : 'WoodyWoodpecker_2019-04-2400.57.24', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WoodyWoodpecker/', 'name' : 'WoodyWoodpecker_2019-04-2400.58.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WoodyWoodpecker/', 'name' : 'WoodyWoodpecker_2019-04-2400.59.37', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WoodyWoodpecker/', 'name' : 'WoodyWoodpecker_2019-04-2401.01.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.17.43', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.20.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.21.38', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.32.24', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.33.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.34.14', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.36.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-04-2400.37.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mickey/', 'name' : 'Mickey_2019-042400.16.00', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.13.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.16.07', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.21.35', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.22.54', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.24.15', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.25.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.27.06', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.28.29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.30.07', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.32.01', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.33.14', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.34.14', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.35.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.36.00', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.37.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.38.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.39.17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.41.01', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.42.10', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.44.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.45.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.47.02', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PlasticsInventor/', 'name' : 'plasticsInventor_2019-04-2200.51.16', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.12.00', 'set': 'm'},
				{ 'trigger' : 'w', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.13.24', 'set': 'm'},
				{ 'trigger' : 'e', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.16.04', 'set': 'm'},
				{ 'trigger' : 'r', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.17.39', 'set': 'm'},
				{ 'trigger' : 't', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.19.02', 'set': 'm'},
				{ 'trigger' : 'y', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.20.28', 'set': 'm'},
				{ 'trigger' : 'u', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.21.52', 'set': 'm'},
				{ 'trigger' : 'i', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.23.13', 'set': 'm'},
				{ 'trigger' : 'o', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.23.58', 'set': 'm'},
				{ 'trigger' : 'p', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.25.20', 'set': 'm'},
				{ 'trigger' : 'a', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.26.47', 'set': 'm'},
				{ 'trigger' : 's', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.27.47', 'set': 'm'},
				{ 'trigger' : 'd', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.29.21', 'set': 'm'},
				{ 'trigger' : 'f', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.31.20', 'set': 'm'},
				{ 'trigger' : 'g', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.33.43', 'set': 'm'},
				{ 'trigger' : 'h', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.34.37', 'set': 'm'},
				{ 'trigger' : 'j', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.37.12', 'set': 'm'},
				{ 'trigger' : 'k', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.38.33', 'set': 'm'},
				{ 'trigger' : 'l', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.39.38', 'set': 'm'},
				{ 'trigger' : 'z', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.40.42', 'set': 'm'},
				{ 'trigger' : 'x', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.41.37', 'set': 'm'},
				{ 'trigger' : 'c', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.42.52', 'set': 'm'},
				{ 'trigger' : 'v', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.44.48', 'set': 'm'},
				{ 'trigger' : 'b', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.47.33', 'set': 'm'},
				{ 'trigger' : 'n', 'location' : 'BettyBoop/', 'name' : 'bettyBoop_2019-04-2401.48.21', 'set': 'm'},
			]
		},
		{
			"id" : 20,
			"trigger": "u",
			"name" : "Wonder Twins",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_downhillWagon', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump3', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fists_beach', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_formOfWater_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_jayna_transforms_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_spiralSpin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_transforming', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_transforming_o', 'set': 'm'},
			]
		},
		{
			"id" : 21,
			"trigger": "v",
			"name" : "Mushrooms - Trumpet",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_1_fx2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_2_fx2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_2_fx_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_5_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_6_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_7_fx_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_o', 'set': 'm'},
				{ 'trigger' : 'w', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_transparent_o', 'set': 'm'},
				{ 'trigger' : 'e', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-2_o', 'set': 'm'},
				{ 'trigger' : 'r', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-2_transparent_o', 'set': 'm'},
				{ 'trigger' : 't', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-3_o', 'set': 'm'},
				{ 'trigger' : 'a', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-3_transparent_o', 'set': 'm'},
				{ 'trigger' : 's', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-4_o', 'set': 'm'},
				{ 'trigger' : 'd', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-4_transparent_o', 'set': 'm'},
			]
		},
		{
			"id" : 22,
			"trigger": "w",
			"name" : "HammerMan",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_dancingWaterTower_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_everyoneDancingPlaying_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammerDancing2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammerDancing3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammerDancing4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammerFeet2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammerFeetDancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammerFeet_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammer_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammer_tiledLogos_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_hammer_twoFemaleDancers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_intro_dancing_tvImages_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_intro_shoes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_kid_keytar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_kidsDancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'hammerman_kids_dancingPlaying_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'hammerman/', 'name' : 'psa_dancing_fruitsVeggies_o', 'set': 'm'},
			]
		},
		{
			"id" : 23,
			"trigger": "x",
			"name" : "Misc 4th Street Vine",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'abc-start_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'att_glowing_wired', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'bw_striped_cube_spin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'bw_stripes_spin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'candyBar_happyFace_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'city-grid-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'city-grid_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'colored_rectangular_dance', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'crashing_cars_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'electro_pyramid_zoom', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'eye_laser_sparkles_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'eye_lasers_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_computer_flashing2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_computer_flashing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_flashing_colorBars_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_spinningStripes_disabledLasers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_spinningStripes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_tvScreen_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'forbidden_world_hyperspace2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'forest-forgery-1-B-FX1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'forest-forgery-2-F2-FX_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_collar_making_machine2_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_collar_making_machine_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_father_collar_making_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_rocket_factory_lights_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'glowing-cube_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'golden-flows_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'grid-open-doors_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'japan_electrifying_organs', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'japan_explosion_eray_tunnel_zoom_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'john-whitney-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'john-whitney-5_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'kaleidoscope_pointed_muted', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'lit_wired_tunnel_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'man_speedos_walking_o', 'set': 'm'}
			]
		},
		{
			"id" : 24,
			"trigger": "y",
			"name" : "4th street cont",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_kid_zap_robot_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_robot_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_robot_walk_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_robot_zap_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_girls_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_light_zoom_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_light_zoom_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_running_light_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'pbs-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'pbs-5_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'rainbow_hypnotic_circles_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'rainbow_sparkler_zoom', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'rainbow_spinning_circles', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'robot_woman_head_back_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'silverhawks_2019-01-26 00.29.53', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'spinning-rainbow-person_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'spinning_space_planes', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'star_explosion_bubbles', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationId_black_hole_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationId_star_tunnel_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationId_star_tunnel_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationLogo_spinning_globe_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'tron_grid_flyover_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'tron_zoom-into-grid_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'ttriangular_infinity_morph_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'tvshow_man_floating_triangle_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'walking-block-man', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'walking_o', 'set': 'm'},
			]
		},
		{
			"id" : 25,
			"trigger": "z",
			"name" : "SpiralZone",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.39.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.40.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.42.25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.46.59', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.50.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.51.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.53.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.55.41', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.56.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.59.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.00.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.02.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.03.53', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.05.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.07.35', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.08.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.09.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.11.29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.12.43', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.13.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.15.40', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.17.53', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.18.48', 'set': 'm'},
			]
		},
	]
}
