// GifJay v.0.8.9

// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// USER SETTINGS
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
var midiOn = true;
var overlaysEnabled = true;

// OVERLAYS
const overlays = [
	{ 'trigger' : '1', 'location' : 'overlays', 'name' : 'clubMutoid_logo_ani.gif'},
	// { 'trigger' : '2', 'location' : 'overlays', 'name' : 'onymico_logo_black_ani.gif'},
	// { 'trigger' : '3', 'location' : 'overlays', 'name' : 'manAMAchine_logo_black_ani.gif'},
]

// GIF BINS
const banks = {
	"bank" : [
		{
			"id" : 0,
			"trigger": ")",
			"name" : "Backgrounds 1",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-1_transparent_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-2_transparent_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-3_transparent_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'FullTimeTrumpet/', 'name' : 'full-time-trumpet-FX-4_transparent_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Ferrofluid/', 'name' : 'ferrofluid-burst_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Ferrofluid/', 'name' : 'ferrofluid-pingpong-1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Ferrofluid/', 'name' : 'ferrofluid-pingpong-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Ferrofluid/', 'name' : 'ferrofluid-pingpong-3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Ferrofluid/', 'name' : 'ferrofluid-symetrical-dance-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Driving/', 'name' : 'driving_y_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_space_comets_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_1_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_2_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_3_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'CanyonFly/', 'name' : 'canyon_fly_3_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.04.28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_flythrough_blocky_caverns', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.17.18', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.21.01', 'set': 'm'},
			]
		},
		{
			"id" : 1,
			"trigger": "!",
			"name" : "Backgrounds 2",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'abc-start_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'att_glowing_wired', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'city-grid-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'city-grid_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'colored_rectangular_dance', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'electro_pyramid_zoom', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_flashing_colorBars_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_spinningStripes_disabledLasers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_spinningStripes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_tvScreen_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'forbidden_world_hyperspace2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'forest-forgery-1-B-FX1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'forest-forgery-2-F2-FX_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'golden-flows_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'grid-open-doors_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'kaleidoscope_pointed_muted', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'lit_wired_tunnel_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'msd_city_flythrough_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'msd_geometric_cave_flythrough_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'msd_lighted_tunnel_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'msd_takeoff_tunnel_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'msd_takeoff_tunnel_withOrb_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'msd_tunnel_twist_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_light_zoom_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_light_zoom_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'spinning_space_planes', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'star_explosion_bubbles', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationId_black_hole_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationId_star_tunnel_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationId_star_tunnel_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'tron_grid_flyover_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'tron_zoom-into-grid_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'ttriangular_infinity_morph_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138-screen-graphics-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138-screen-graphics-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138-screen-head_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138_screen-graphics-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138_screen-graphics_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'thx1138_screen-grid_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'black_white_rays_o', 'set': 'm'},
			]
		},
		{
			"id" : 2,
			"trigger": "@",
			"name" : "Backgrounds 3",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileAug08123439AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileAug08123703AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813455AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813902AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813914AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813937AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813947AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1813957AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul1814555AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_FileJul184611AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814018AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814034AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814415AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814448AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814457AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814510AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814521AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814531AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_Jul1814544AM', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_electrifying_organs', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JapaneseAnims/', 'name' : 'japan_explosion_eray_tunnel_zoom_o', 'set': 'm'},
			]
		},

		{
			"id" : 3,
			"trigger": "#",
			"name" : "Foregrounds 1 - Dancing",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_friends_dancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_sabrina_dances_withClone_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_sabrina_friend_dances_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_dancing_pandas2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_dancing_pandas_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'sabrinaTeenageWitch_cu_legs_dancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'jerryLewis_runningAroungScreen_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Archies/', 'name' : 'archies_dancing_kids_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfit_fire_dance2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_misfit_fire_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingFire_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingFire_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines2_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines_keithGuitar_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingOutlines_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingWavyLines_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_dancingWavyLines_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurieDancingTransformation_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_discoDancers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_keyopDiscoDance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_keyopDiscoDance2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_markFlipping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_markOnGlass_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessDiscoDance4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'battleOfThePlanets_princessFlipping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammer_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammer_twoFemaleDancers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammerDancing2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammerDancing3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammerDancing4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammerFeet_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammerFeet2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_hammerFeetDancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_intro_shoes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hammerman/', 'name' : 'hammerman_kidsDancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Heman/', 'name' : 'heman_dodgingLasers_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_girls_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'digitalDance_seq4_o', 'set': 'm'}
			]
		},
		{
			"id" : 4,
			"trigger": "$",
			"name" : "Foregrounds 2 - Robots and Stuff",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'robot_woman_head_back_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'tvshow_man_floating_triangle_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_kid_zap_robot_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_robot_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_robot_walk_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'nintendo_gameboy_robot_zap_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_collar_making_machine2_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_collar_making_machine_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_father_collar_making_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fp_rocket_factory_lights_REDO_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'man_speedos_walking_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'mannMachine_robotHead_laserEyes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'mannMachine_robotHead_spin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'mannMachine_robotSpin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobot_flashingRobot_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobots _robot_boomerang_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobots_transformMan_explosion_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'ronniesRobots_transformMan_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'star-rider-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Robots/', 'name' : 'tvbreak_robot_corridor', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'pbs-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'pbs-5_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_transform_constellation_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'fantasticVoyage_computer_flashing2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'space_d', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'space_e', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'space_g', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'space_k', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'space_l', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'space_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'space_p', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Space/', 'name' : 'tvbreak_robot_corridor', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_intro_alien_hop_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_intro_rocketFlying2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_intro_rocketFlying_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotDancing_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotHandOnHead_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotsRunningSmashed_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JosiePussycatsSpace/', 'name' : 'josiePussycatsSpace_robotsRunning_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.39.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.40.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.50.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.51.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.53.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.55.41', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.56.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2600.59.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.00.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.02.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.03.53', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.05.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.08.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2601.09.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.11.29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.12.43', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.13.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.15.40', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.17.53', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SpiralZone/', 'name' : 'spiralZone_2019-01-2603.18.48', 'set': 'm'},
			]
		},

		{
			"id" : 5,
			"trigger": "%",
			"name" : "Foregrounds 3",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_1_fx2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_2_fx2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_2_fx_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_5_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_6_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Mushrooms/', 'name' : 'mushroom_7_fx_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'glowing-cube_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'stationLogo_spinning_globe_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Eyes/', 'name' : 'eyes_r_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Eyes/', 'name' : 'eyes_s_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'eye_laser_sparkles_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'eye_lasers_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'walking-block-man', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'walking_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'crashing_cars_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'spinning-rainbow-person_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'candyBar_happyFace_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_jumping_off_cliff_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Bravestarr/', 'name' : 'bravestarr_mind_control_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_lightBeams_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_trippyGalaxy_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'BotP/', 'name' : 'botp_trippyRainbowTunnel_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_flashing_stage_lights_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Jem/', 'name' : 'jem_lips_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JacksonFive/', 'name' : 'jackson5_flashingSun_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'JacksonFive/', 'name' : 'jackson5_walkingSunSilhouettes_shadow_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_a', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_b', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_c', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_d', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_e', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_f', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_g', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_h', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_i', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'DancingTrails/', 'name' : 'dancingTrails_j', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'orbots_running_light_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2721.23.59', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2721.26.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2721.29.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.47.34', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.51.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.53.34', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2818.56.17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2819.02.47', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2819.03.42', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2821.39.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MonkeyMagic/', 'name' : 'monkeyMagic_2019-02-2821.41.10', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'face_flashes', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'flipping_eyes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'punch_face_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'sun_shining_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'vibrating_hand_shake', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'water_dripping_flashes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'SallyKruickshank/', 'name' : 'zoom_through_eyes_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'StarRider/', 'name' : 'star-rider-1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'StarRider/', 'name' : 'star-rider-2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'StarRider/', 'name' : 'star-rider-3', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'StarRider/', 'name' : 'star-rider-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'StarRider/', 'name' : 'star-rider-5', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'StarRider/', 'name' : 'star-rider-6', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'StarRider/', 'name' : 'star-rider-7', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Commercials/', 'name' : 'commercial_handsUp_headBeam', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Commercials/', 'name' : 'commercial_watch', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Commercials/', 'name' : 'shaving_face_grid', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Commercials/', 'name' : 'sunglasses_zoom', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Commercials/', 'name' : 'u', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'bus-jump-ramp_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'cat-pooping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'dancing-hulk_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'flying-trucks2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'garage-gorilla_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'garage-tiger-running_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'gorilla-punching-egg_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'hulk-step-walk_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'multiple-buses-jumping_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'ramp-jumping-trucks_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'spinning-trucks_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'superhero-banana-car-fx_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'superhero-toilet-dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'swimming-hulk-fruit-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'KidVideos/', 'name' : 'swimming-hulk-fruit_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-explosion-5_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'NuclearExplosions/', 'name' : 'nuclear-house-explosion-1_o', 'set': 'm'},
			]
		},

		{
			"id" : 6,
			"trigger": "^",
			"name" : "Foregrounds 4 - Bands",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_bobby_drums_o', 'set': 'm'},
				{ 'trigger' : 'r', 'location' : 'Archies/', 'name' : 'archies_jughead_drums_o', 'set': 'm'},
				{ 'trigger' : 't', 'location' : 'Archies/', 'name' : 'archies_jughead_drums_silhouette_o', 'set': 'm'},
				{ 'trigger' : 'a', 'location' : 'Jem/', 'name' : 'jem_drumming_fire_o', 'set': 'm'},
				{ 'trigger' : 's', 'location' : 'Jem/', 'name' : 'jem_drumming_o', 'set': 'm'},
				{ 'trigger' : 'd', 'location' : 'Jem/', 'name' : 'jem_drums2_o', 'set': 'm'},
				{ 'trigger' : 'f', 'location' : 'Jem/', 'name' : 'jem_drums_o', 'set': 'm'},
				{ 'trigger' : 'g', 'location' : 'Jem/', 'name' : 'jem_hittingDrumPads_o', 'set': 'm'},
				{ 'trigger' : 'z', 'location' : 'Bravestarr/', 'name' : 'bravestarr_man_drumming_o', 'set': 'm'},
				{ 'trigger' : 'x', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_drumsticksPlaying_o', 'set': 'm'},
				{ 'trigger' : 'c', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_drumsticksPlaying_o_t', 'set': 'm'},
				{ 'trigger' : 'v', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_chris_drums2_o', 'set': 'm'},
				{ 'trigger' : 'b', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_chris_drums_o', 'set': 'm'},
				{ 'trigger' : 'e', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_jan_keyboards2_o', 'set': 'm'},
				{ 'trigger' : 'r', 'location' : 'AnimatedBands/', 'name' : 'bradyBunch_jan_keyboards_o', 'set': 'm'},
				{ 'trigger' : 'y', 'location' : 'Archies/', 'name' : 'archies_veronica_keyboard_o', 'set': 'm'},
				{ 'trigger' : 'u', 'location' : 'Archies/', 'name' : 'archies_veronica_keyboard_silhouette2_o', 'set': 'm'},
				{ 'trigger' : 'a', 'location' : 'Archies/', 'name' : 'archies_veronica_keyboard_silhouette_o', 'set': 'm'},
				{ 'trigger' : 's', 'location' : 'Jem/', 'name' : 'jem_keyboard_o', 'set': 'm'},
				{ 'trigger' : 'd', 'location' : 'Bravestarr/', 'name' : 'bravestarr_woman_keytar_o', 'set': 'm'},
				{ 'trigger' : 'f', 'location' : 'Bravestarr/', 'name' : 'bravestarr_woman_playing_keytar_o', 'set': 'm'},
				{ 'trigger' : 'g', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_laurie_keyboards2_o', 'set': 'm'},
				{ 'trigger' : 'z', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_shirley_fingers_keyboard_o', 'set': 'm'},
				{ 'trigger' : 'x', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_shirley_keyboards_cu_o', 'set': 'm'},
				{ 'trigger' : 'c', 'location' : 'PartridgeFamilySpace/', 'name' : 'partridgeFamilySpace_shirley_keyboards_o', 'set': 'm'},
				{ 'trigger' : 'n', 'location' : 'Hammerman/', 'name' : 'hammerman_kid_keytar_o', 'set': 'm'}
			]
		},

		{
			"id" : 7,
			"trigger": "&",
			"name" : "Foregrounds 5 - Aerobics",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_10', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_11', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_13', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_14', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_15', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_16', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_18', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_19', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_24', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_27', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_3', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_30', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_31', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_4', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_5', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_6', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_7', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_8', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_9', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_group1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobic-trails-1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobic-trails-2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobic-trails-3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobic-trails-4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics-leg-warmer-feet_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics_2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics_4_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics_5_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics_group_1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics_group_2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : '4thStreetVine/', 'name' : 'aerobics_group_3_o', 'set': 'm'},
			]
		},

		{
			"id" : 8,
			"trigger": "*",
			"name" : "Foregrounds 6 - Hercules",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_body_flip_flash', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_cave_eyes_flash_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_dinosaur_hercules_sword_twirl', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_dinosaur_transform', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_explosion_stars', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_fire_people_cu_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_fling_monsters_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_gorilla_dinosaur_fight', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_grabs_bolt', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_green_beams', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_head_swirlies', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_hercules_transport', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_king', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_king_explosion', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_king_hercules_fight', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_king_hercules_fight2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_king_laser_eyes', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_king_swing_beam', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_king_swing_beam2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_knight', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_knightHerculesFight', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_knightHerculesFight2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_knightHerculesFight3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_knightLyte', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_lightning_skull_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_mermaid_eye_beams_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_movie_intro_1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_movie_intro_eye2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_movie_intro_eye3_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_punch_beam', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_punch_green_monster', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_shield_block_beam', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_shield_block_beam2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_shooting_star_crater_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_space_tunnel_explosion_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_space_two_women_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_star_explosions', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_sword', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_sword_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_transform_constellation_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_transforms_gorilla_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_undersea_swimming_beams', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_undersea_walking', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_woman_arms_beam_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_woman_space_trails', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_woman_space_trails_arms2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_woman_space_trails_arms_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_woman_space_trails_dance_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_woman_stars_spinning', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_women_sparkle_shower2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_women_sparkle_shower_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Hercules/', 'name' : 'hercules_women_sparkles_fadeOut_o', 'set': 'm'},
			]
		},
		{
			"id" : 9,
			"trigger": "(",
			"name" : "Foregrounds 7 - Mission Space Delta",
			"enabled" : true,
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.26.06', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.40.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.43.01', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.48.12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.55.43', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0316.57.50', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.05.28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.07.47', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.15.09', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.19.25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.23.44', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.25.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.37.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.52.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.53.28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.57.51', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0317.59.10', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.01.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.07.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.10.38', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0318.16.34', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.18.23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.20.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.52.32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.54.57', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0319.58.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.00.48', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.02.58', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.04.21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.07.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.15.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.20.16', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.29.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0320.38.00', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0321.47.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.09.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.13.57', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.16.05', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.30.08', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.37.31', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.43.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.48.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0322.50.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.27.03', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.30.23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.36.04', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.39.32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.41.56', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.43.46', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.46.22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0323.48.41', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.04.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.06.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.18.26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.26.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.27.52', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.30.38', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.32.57', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.36.40', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.39.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.43.17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0400.51.49', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.15.03', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.17.36', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.24.07', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_2018-03-0401.26.20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_22018-03-0318.08.55', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_alienWoman_flyAround_orb2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_alienWoman_flyAround_orb_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_bat_punch_chop_robots_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_chased_by_wave', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_chased_by_wave2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_explosing_balls', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_flashing_control_room', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_floating_hallway', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_kicking_robots_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_man_fighting_robots', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_orb_drags_rainbowRings_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_orb_glowing_o_t', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_pink_space_clouds', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_running_space_forest_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_ship_flying_into_spaceClouds_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'MissionSpatialeDelta2/', 'name' : 'msd_space_forest_log_jumping_o', 'set': 'm'},
			]
		}
	]
}

setsArray = [];

var effectsOn = [];
// var filtersOn = [];
var beatTime = 2000;
var beatSpeed = 1000;
var titlePageOn = 0;
var sameSameConstant = 2;
titlePageName = 'title-1.gif';

filters = {
	"strings": [
		{"value": ""},
		{"value": ""}
	],
  "filter" : [
    {
      "name": "Invert",
      "slugName": "invert",
      "trigger": "7",
      "min": 0,
      "max": 1,
      "unit": "",
      "enabled": true,
      "on": 0,
      "stage": [
        { "value": "" },
        { "value": "" }
      ]
    },
    {
      "name": "Saturate",
      "slugName": "saturate",
      "trigger": "8",
      "min": 1,
      "max": 100,
      "unit": "",
      "enabled": true,
      "on": 0,
      "stage": [
        { "value": "" },
        { "value": "" }
      ]
    },
    {
      "name": "Hue Rotate",
      "slugName": "hue-rotate",
      "trigger": "9",
      "min": 0,
      "max": 360,
      "unit": "deg",
      "enabled": true,
      "on": 0,
      "stage": [
        { "value": "" },
        { "value": "" }
      ]
    },
    {
      "name": "Blur",
      "slugName": "blur",
      "trigger": "0",
      "min": 0,
      "max": 5,
      "unit": "px",
      "enabled": true,
      "on": 0,
      "stage": [
        { "value": "" },
        { "value": "" }
      ]
    }
  ]
}

bankerSets = {
	"set" : [
		{
			"name" : "Eyeballs",
			"trigger" : "a",
			"gifs" : [
				{'location' : '4thStreetVine/', 'name' : 'robot_woman_head_back_o' },
				{'location' : '4thStreetVine/', 'name' : 'electro_pyramid_zoom' },
				{'location' : '4thStreetVine/', 'name' : 'eye_laser_sparkles_o' },
				{'location' : '4thStreetVine/', 'name' : 'eye_lasers_1_o' },
				{'location' : 'BathBombs/', 'name' : 'bathbomb-boomerang_o'},
				{'location' : 'BathBombs/', 'name' : 'bathbomb-galaxy-1_o'},
				{'location' : 'BathBombs/', 'name' : 'bathbomb-galaxy-2_o'},
				{'trigger' : 'q', 'location' : 'BathBombs/', 'name' : 'bathbomb-slow-1_o'}
			]
		},
		{
			"name" : "Hercules",
			"trigger" : "b",
			"gifs" : [
				{'location' : 'Hercules/', 'name' : 'hercules_mermaid_eye_beams_o'},
				{'location' : 'Hercules/', 'name' : 'hercules_movie_intro_eye2_o'},
				{'location' : 'Hercules/', 'name' : 'hercules_shooting_star_crater_o'},
				{'location' : 'Hercules/', 'name' : 'hercules_space_tunnel_explosion_o'},
				{'location' : 'Hercules/', 'name' : 'hercules_woman_arms_beam_o'},
				{'location' : 'Hercules/', 'name' : 'hercules_woman_space_trails_dance_o'},
				{'location' : 'Hercules/', 'name' : 'hercules_women_sparkle_shower_o'},
				{'location' : 'Hercules/', 'name' : 'hercules_women_sparkles_fadeOut_o'}
			]
		},
		{
			"name" : "Aerobics Competition",
			"trigger" : "c",
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_10', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_11', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_12', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_13', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_14', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_15', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_16', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_17', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_18', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_19', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_2', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_20', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_21', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_22', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_23', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_24', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_25', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_26', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_27', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_28', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_29', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_3', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_30', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_31', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_32', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_4', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_5', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_6', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_7', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_8', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_9', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_group1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'Aerobics/', 'name' : 'aerobicsCompetition_group1_o', 'set': 'm'}
			]
		},
		{
			"name" : "Wonder Twins",
			"trigger" : "d",
			"gifs" : [
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_downhillWagon', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump1', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump1_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump2_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fistBump3', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_fists_beach', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_formOfWater_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_jayna_transforms_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_spiralSpin_o', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_transforming', 'set': 'm'},
				{ 'trigger' : 'q', 'location' : 'WonderTwins/', 'name' : 'wondertwins_transforming_o', 'set': 'm'},
			]
		},
	]
}

var blendModes = {
	"mix" : [
		{ "name": "multiply", "trigger": "1", "enabled": true },
		{ "name": "darken", "trigger": "1", "enabled": true },
		{ "name": "lighten", "trigger": "1", "enabled": true },
		{ "name": "color-dodge", "trigger": "1", "enabled": true },
		{ "name": "color-burn", "trigger": "1", "enabled": true },
		{ "name": "hard-light", "trigger": "1", "enabled": true },
		{ "name": "soft-light", "trigger": "1", "enabled": true },
		{ "name": "difference", "trigger": "1", "enabled": true },
		{ "name": "exclusion", "trigger": "1", "enabled": true },
		{ "name": "hue", "trigger": "1", "enabled": true },
		{ "name": "saturation", "trigger": "1", "enabled": true },
		{ "name": "color", "trigger": "1", "enabled": true },
		{ "name": "luminosity", "trigger": "1", "enabled": true }
	]
}

stageArray = ['sf', 'st'];
shapeArray = ['circle','triangle','rhombus','octagon','close','frame','rabbet'];
flipArray = ['rotateX(180deg)','rotateX(-180deg)','rotateY(180deg)','rotateY(-180deg)'];
blendModeSwitcherArray = ['multiply','darken','lighten','color-dodge','color-burn',
  'hard-light','soft-light','difference','exclusion','hue','saturation','color','luminosity'];
blendModeArray = ['screen','overlay'];
effectArray = ['invert','saturation','brightness','hue-rotate','blur'];

bankArray = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r'];
bgPosA = ['top', 'bottom'];
bgPosB = ['right', 'left'];
repeatArray = ['repeat', 'no-repeat'];
borderArray = ['dotted', 'dashed', 'double', 'solid', 'ridge'];

var app = {
	settings: {
		effects: {
			kaleidoscope: { name: 'kaleidoscope', enabled: true, filterKey: "1" },
			sameSame: { name: 'sameSame', enabled: true, filterKey: "3" },
			stgFade: { name: 'stgFade', enabled: true, filterKey: "4" },
			invert: { name: 'invert', enabled: true, filterKey: "7" },
			saturator: { name: 'saturator', enabled: true, filterKey: "8" },
			hueShift: { name: 'hueShift', enabled: true, filterKey: "9" },
			blurry: { name: 'blurry', enabled: true, filterKey: "0" }
		}
	}
}

var appFX = app.settings.effects;
