{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_a'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_g'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_i'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_n'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_o'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_p'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_q copy'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_q'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_s copy'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_s'},
{ 'trigger' : 'q', 'location' : 'Flythroughs/', 'name' : 'flythrough_t'},
